#!/usr/bin/with-contenv bash

# Set Defaults
OPCACHE_MEM_SIZE=${OPCODE_MEM_SIZE:-"128"}
PHP_LOG_LEVEL=${PHP_LOG_LEVEL:-"notice"}
PHP_MEMORY_LIMIT=${PHP_MEMORY_LIMIT:-"128M"}
PHP_TIMEOUT=${PHP_TIMEOUT:-"180"}
UPLOAD_MAX_SIZE=${UPLOAD_MAX_SIZE:-"2G"}

PHP_ENABLE_CURL=${PHP_ENABLE_CURL:-"TRUE"}
PHP_ENABLE_LDAP=${PHP_ENABLE_LDAP:-"TRUE"}
PHP_ENABLE_MBSTRING=${PHP_ENABLE_MBSTRING:-"TRUE"}
PHP_ENABLE_GETTEXT=${PHP_ENABLE_GETTEXT:-"FALSE"}
PHP_ENABLE_OPENSSL=${PHP_ENABLE_OPENSSL:-"TRUE"}
PHP_ENABLE_PHAR=${PHP_ENABLE_PHAR:-"TRUE"}
PHP_ENABLE_POSIX=${PHP_ENABLE_POSIX:-"FALSE"}
PHP_ENABLE_SESSION=${PHP_ENABLE_SESSION:-"TRUE"}
PHP_ENABLE_IMAGICK=${PHP_ENABLE_IMAGICK:-"FALSE"}
PHP_ENABLE_IMAP=${PHP_ENABLE_IMAP:-"TRUE"}

# Adjust PHP Runtime Variables
sed -i -e "s/<OPCACHE_MEM_SIZE>/$OPCACHE_MEM_SIZE/g" /etc/php7/conf.d/00_opcache.ini
sed -i -e "s/<PHP_MEMORY_LIMIT>/$PHP_MEMORY_LIMIT/g" /etc/php7/php-fpm.conf
sed -i -e "s/<PHP_MEMORY_LIMIT>/$PHP_MEMORY_LIMIT/g" /etc/php7/php.ini
sed -i -e "s/<PHP_TIMEOUT>/$PHP_TIMEOUT/g" /etc/php7/php.ini
sed -i -e "s/<UPLOAD_MAX_SIZE>/$UPLOAD_MAX_SIZE/g" /etc/php7/php-fpm.conf
sed -i -e "s/<UPLOAD_MAX_SIZE>/$UPLOAD_MAX_SIZE/g" /etc/php7/php.ini

# Timezone Config
echo 'date.timezone='`cat /etc/timezone` >> /etc/php7/conf.d/timezone.ini

# Disable Extensions
PHP_PLUGINS_ENABLED=`set -o posix; set | sort | grep PHP_ENABLE_ | grep TRUE |sed -e 's/PHP_ENABLE_//g' | sed -e 's/=TRUE//g' | awk -vRS="" -vOFS=', ' '$1=$1' | tr A-Z a-z`

echo '** PHP-FPM Preparing to start with the following plugins enabled: '$PHP_PLUGINS_ENABLED

if [ "$PHP_ENABLE_CURL" != "TRUE" ]; then rm -rf /etc/php7/00_curl.ini ; fi;
if [ "$PHP_ENABLE_LDAP" != "TRUE" ]; then rm -rf /etc/php7/00_ldap.ini ; fi;
if [ "$PHP_ENABLE_MBSTRING" != "TRUE" ]; then rm -rf /etc/php7/00_mbstring.ini ; fi;
if [ "$PHP_ENABLE_OPENSSL" != "TRUE" ]; then rm -rf /etc/php7/00_openssl.ini ; fi;
if [ "$PHP_ENABLE_POSIX" != "TRUE" ]; then  rm -rf /etc/php7/00_posix.ini; fi;
if [ "$PHP_ENABLE_SESSION" != "TRUE" ]; then rm -rf /etc/php7/00_session.ini ; fi;
if [ "$PHP_ENABLE_GETTEXT" != "TRUE" ]; then rm -rf /etc/php7/00_gettext.ini; fi;
if [ "$PHP_ENABLE_IMAGICK" != "TRUE" ]; then rm -rf /etc/php7/imagick.ini ; fi;
if [ "$PHP_ENABLE_IMAP" != "TRUE" ]; then rm -rf /etc/php7/00_imap.ini ; fi;

sed -i -e "s/<PHP_LOG_LEVEL>/$PHP_LOG_LEVEL/g" /etc/php7/php-fpm.conf

mkdir -p /www/logs/php-fpm
chown -R nginx /www/logs/php-fpm

mkdir -p /tmp/state
touch /tmp/state/init-20-php-fpm
